# Generated by Django 5.2.8 on 2025-11-30 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(max_length=255)),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("year", models.IntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "description", "genre", "year"),
                        name="unique_movie_full",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_movies",
                    models.ManyToManyField(
                        blank=True, related_name="recommended_to", to="api.movie"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watch_list",
                    models.ManyToManyField(
                        blank=True, related_name="in_watchlists", to="api.movie"
                    ),
                ),
                (
                    "watched_movies",
                    models.ManyToManyField(
                        blank=True, related_name="watched_by", to="api.movie"
                    ),
                ),
            ],
        ),
    ]
